M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-09-01T03:22:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-01T03:22:54+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X131.1Y-6.51
X136.9Y-6.51
T2
X4.0Y-4.0
X4.0Y-71.0
X146.0Y-4.0
X146.0Y-71.0
M30
